inherit_from: .rubocop_todo.yml
AllCops:
  TargetRubyVersion: 2.3
  Include:
    - '**/*.gemspec'
    - '**/Gemfile'
    - '**/Rakefile'
    - '**/*.rake'
Rails:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/ClassCheck:
  Enabled: false
Style/SignalException:
  Enabled: false
Style/IndentArray:
  EnforcedStyle: consistent
Style/IndentHash:
  EnforcedStyle: consistent
Style/FirstParameterIndentation:
  EnforcedStyle: consistent
Style/CaseIndentation:
  IndentWhenRelativeTo: end
Style/Alias:
  EnforcedStyle: prefer_alias_method
Lint/EndAlignment:
  AlignWith: variable
Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Style/SpaceInLambdaLiteral:
  Enabled: false
Bundler/OrderedGems:
  Enabled: false
