inherit_from: .rubocop_todo.yml
AllCops:
  TargetRubyVersion: 2.3
  Include:
    - "**/*.gemspec"
    - "**/Gemfile"
    - "**/Rakefile"
    - "**/Guardfile"
    - "**/*.rake"
Metrics/LineLength:
  Enabled: false
Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/ClassCheck:
  Enabled: false
Style/SignalException:
  Enabled: false
Style/Alias:
  EnforcedStyle: prefer_alias_method
Layout/CaseIndentation:
  EnforcedStyle: end
Layout/EndAlignment:
  EnforcedStyleAlignWith: variable
Layout/IndentFirstArgument:
  EnforcedStyle: consistent
Layout/IndentFirstArrayElement:
  EnforcedStyle: consistent
Layout/IndentFirstHashElement:
  EnforcedStyle: consistent
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Layout/SpaceInLambdaLiteral:
  Enabled: false
Bundler/OrderedGems:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - "spec/**/*.rb"
Lint/Void:
  Exclude:
    - "bin/bench_ruby_comparisons"
    - "bin/bench_ruby_binary"
